name: pre-commit

on:
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: pre-commit/action@v2.0.0
      with:
        extra_args: --all-files --hook-stage push
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        PYTHONPATH: "."
